name: portal
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
    
      - name: Run tests
        run: yarn test
